var annotated_dup =
[
    [ "OpenServiceBroker", "namespace_open_service_broker.html", [
      [ "Bindings", "namespace_open_service_broker_1_1_bindings.html", [
        [ "IServiceBindingBase", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_base.html", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_base" ],
        [ "IServiceBindingBlocking", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_blocking.html", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_blocking" ],
        [ "IServiceBindingDeferred", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_deferred.html", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_deferred" ],
        [ "IServiceBindingDeferredEndpoint", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_deferred_endpoint.html", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_deferred_endpoint" ],
        [ "IServiceBindingEndpoint", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_endpoint.html", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_endpoint" ],
        [ "IServiceBindingEndpointBase", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_endpoint_base.html", "interface_open_service_broker_1_1_bindings_1_1_i_service_binding_endpoint_base" ],
        [ "ServiceBinding", "class_open_service_broker_1_1_bindings_1_1_service_binding.html", null ],
        [ "ServiceBindingAsyncOperation", "class_open_service_broker_1_1_bindings_1_1_service_binding_async_operation.html", null ],
        [ "ServiceBindingBase", "class_open_service_broker_1_1_bindings_1_1_service_binding_base.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_base" ],
        [ "ServiceBindingBlockingEndpoint", "class_open_service_broker_1_1_bindings_1_1_service_binding_blocking_endpoint.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_blocking_endpoint" ],
        [ "ServiceBindingContext", "class_open_service_broker_1_1_bindings_1_1_service_binding_context.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_context" ],
        [ "ServiceBindingDeferredEndpoint", "class_open_service_broker_1_1_bindings_1_1_service_binding_deferred_endpoint.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_deferred_endpoint" ],
        [ "ServiceBindingEndpointBase", "class_open_service_broker_1_1_bindings_1_1_service_binding_endpoint_base.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_endpoint_base" ],
        [ "ServiceBindingPollingEndpoint", "class_open_service_broker_1_1_bindings_1_1_service_binding_polling_endpoint.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_polling_endpoint" ],
        [ "ServiceBindingRequest", "class_open_service_broker_1_1_bindings_1_1_service_binding_request.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_request" ],
        [ "ServiceBindingResource", "class_open_service_broker_1_1_bindings_1_1_service_binding_resource.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_resource" ],
        [ "ServiceBindingResourceObject", "class_open_service_broker_1_1_bindings_1_1_service_binding_resource_object.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_resource_object" ],
        [ "ServiceBindingsController", "class_open_service_broker_1_1_bindings_1_1_service_bindings_controller.html", "class_open_service_broker_1_1_bindings_1_1_service_bindings_controller" ],
        [ "ServiceBindingVolumeMount", "class_open_service_broker_1_1_bindings_1_1_service_binding_volume_mount.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_volume_mount" ],
        [ "ServiceBindingVolumeMountDevice", "class_open_service_broker_1_1_bindings_1_1_service_binding_volume_mount_device.html", "class_open_service_broker_1_1_bindings_1_1_service_binding_volume_mount_device" ]
      ] ],
      [ "Catalogs", "namespace_open_service_broker_1_1_catalogs.html", [
        [ "Catalog", "class_open_service_broker_1_1_catalogs_1_1_catalog.html", "class_open_service_broker_1_1_catalogs_1_1_catalog" ],
        [ "CatalogController", "class_open_service_broker_1_1_catalogs_1_1_catalog_controller.html", "class_open_service_broker_1_1_catalogs_1_1_catalog_controller" ],
        [ "DashboardClient", "class_open_service_broker_1_1_catalogs_1_1_dashboard_client.html", "class_open_service_broker_1_1_catalogs_1_1_dashboard_client" ],
        [ "ICatalogService", "interface_open_service_broker_1_1_catalogs_1_1_i_catalog_service.html", "interface_open_service_broker_1_1_catalogs_1_1_i_catalog_service" ],
        [ "IETagProvider", "interface_open_service_broker_1_1_catalogs_1_1_i_e_tag_provider.html", "interface_open_service_broker_1_1_catalogs_1_1_i_e_tag_provider" ],
        [ "ILastModifiedProvider", "interface_open_service_broker_1_1_catalogs_1_1_i_last_modified_provider.html", "interface_open_service_broker_1_1_catalogs_1_1_i_last_modified_provider" ],
        [ "Plan", "class_open_service_broker_1_1_catalogs_1_1_plan.html", "class_open_service_broker_1_1_catalogs_1_1_plan" ],
        [ "SchemaParameters", "class_open_service_broker_1_1_catalogs_1_1_schema_parameters.html", "class_open_service_broker_1_1_catalogs_1_1_schema_parameters" ],
        [ "Schemas", "class_open_service_broker_1_1_catalogs_1_1_schemas.html", "class_open_service_broker_1_1_catalogs_1_1_schemas" ],
        [ "Service", "class_open_service_broker_1_1_catalogs_1_1_service.html", "class_open_service_broker_1_1_catalogs_1_1_service" ],
        [ "ServiceBindingSchema", "class_open_service_broker_1_1_catalogs_1_1_service_binding_schema.html", "class_open_service_broker_1_1_catalogs_1_1_service_binding_schema" ],
        [ "ServiceInstanceSchema", "class_open_service_broker_1_1_catalogs_1_1_service_instance_schema.html", "class_open_service_broker_1_1_catalogs_1_1_service_instance_schema" ]
      ] ],
      [ "Errors", "namespace_open_service_broker_1_1_errors.html", [
        [ "ApiVersionNotSupportedException", "class_open_service_broker_1_1_errors_1_1_api_version_not_supported_exception.html", null ],
        [ "AsyncRequiredException", "class_open_service_broker_1_1_errors_1_1_async_required_exception.html", null ],
        [ "BadRequestException", "class_open_service_broker_1_1_errors_1_1_bad_request_exception.html", null ],
        [ "BrokerException", "class_open_service_broker_1_1_errors_1_1_broker_exception.html", "class_open_service_broker_1_1_errors_1_1_broker_exception" ],
        [ "ConcurrencyException", "class_open_service_broker_1_1_errors_1_1_concurrency_exception.html", null ],
        [ "ConflictException", "class_open_service_broker_1_1_errors_1_1_conflict_exception.html", null ],
        [ "Error", "class_open_service_broker_1_1_errors_1_1_error.html", "class_open_service_broker_1_1_errors_1_1_error" ],
        [ "GoneException", "class_open_service_broker_1_1_errors_1_1_gone_exception.html", null ],
        [ "MaintenanceInfoConflictException", "class_open_service_broker_1_1_errors_1_1_maintenance_info_conflict_exception.html", null ],
        [ "NotFoundException", "class_open_service_broker_1_1_errors_1_1_not_found_exception.html", null ],
        [ "RequiresAppException", "class_open_service_broker_1_1_errors_1_1_requires_app_exception.html", null ],
        [ "StatusBase", "class_open_service_broker_1_1_errors_1_1_status_base.html", "class_open_service_broker_1_1_errors_1_1_status_base" ]
      ] ],
      [ "Instances", "namespace_open_service_broker_1_1_instances.html", [
        [ "IServiceInstanceBase", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_base.html", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_base" ],
        [ "IServiceInstanceBlocking", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_blocking.html", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_blocking" ],
        [ "IServiceInstanceDeferred", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_deferred.html", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_deferred" ],
        [ "IServiceInstanceDeferredEndpoint", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_deferred_endpoint.html", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_deferred_endpoint" ],
        [ "IServiceInstanceEndpoint", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_endpoint.html", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_endpoint" ],
        [ "IServiceInstanceEndpointBase", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_endpoint_base.html", "interface_open_service_broker_1_1_instances_1_1_i_service_instance_endpoint_base" ],
        [ "ServiceInstanceAsyncOperation", "class_open_service_broker_1_1_instances_1_1_service_instance_async_operation.html", "class_open_service_broker_1_1_instances_1_1_service_instance_async_operation" ],
        [ "ServiceInstanceBase", "class_open_service_broker_1_1_instances_1_1_service_instance_base.html", "class_open_service_broker_1_1_instances_1_1_service_instance_base" ],
        [ "ServiceInstanceBlockingEndpoint", "class_open_service_broker_1_1_instances_1_1_service_instance_blocking_endpoint.html", "class_open_service_broker_1_1_instances_1_1_service_instance_blocking_endpoint" ],
        [ "ServiceInstanceContext", "class_open_service_broker_1_1_instances_1_1_service_instance_context.html", "class_open_service_broker_1_1_instances_1_1_service_instance_context" ],
        [ "ServiceInstanceDeferredEndpoint", "class_open_service_broker_1_1_instances_1_1_service_instance_deferred_endpoint.html", "class_open_service_broker_1_1_instances_1_1_service_instance_deferred_endpoint" ],
        [ "ServiceInstanceEndpointBase", "class_open_service_broker_1_1_instances_1_1_service_instance_endpoint_base.html", "class_open_service_broker_1_1_instances_1_1_service_instance_endpoint_base" ],
        [ "ServiceInstanceMetadata", "class_open_service_broker_1_1_instances_1_1_service_instance_metadata.html", "class_open_service_broker_1_1_instances_1_1_service_instance_metadata" ],
        [ "ServiceInstancePollingEndpoint", "class_open_service_broker_1_1_instances_1_1_service_instance_polling_endpoint.html", "class_open_service_broker_1_1_instances_1_1_service_instance_polling_endpoint" ],
        [ "ServiceInstancePreviousValues", "class_open_service_broker_1_1_instances_1_1_service_instance_previous_values.html", "class_open_service_broker_1_1_instances_1_1_service_instance_previous_values" ],
        [ "ServiceInstanceProvision", "class_open_service_broker_1_1_instances_1_1_service_instance_provision.html", "class_open_service_broker_1_1_instances_1_1_service_instance_provision" ],
        [ "ServiceInstanceProvisionRequest", "class_open_service_broker_1_1_instances_1_1_service_instance_provision_request.html", "class_open_service_broker_1_1_instances_1_1_service_instance_provision_request" ],
        [ "ServiceInstanceResource", "class_open_service_broker_1_1_instances_1_1_service_instance_resource.html", "class_open_service_broker_1_1_instances_1_1_service_instance_resource" ],
        [ "ServiceInstancesController", "class_open_service_broker_1_1_instances_1_1_service_instances_controller.html", "class_open_service_broker_1_1_instances_1_1_service_instances_controller" ],
        [ "ServiceInstanceUpdateRequest", "class_open_service_broker_1_1_instances_1_1_service_instance_update_request.html", "class_open_service_broker_1_1_instances_1_1_service_instance_update_request" ]
      ] ],
      [ "ApiVersion", "struct_open_service_broker_1_1_api_version.html", null ],
      [ "AsyncOperation", "class_open_service_broker_1_1_async_operation.html", null ],
      [ "BrokerControllerBase", "class_open_service_broker_1_1_broker_controller_base.html", "class_open_service_broker_1_1_broker_controller_base" ],
      [ "Completable", "class_open_service_broker_1_1_completable.html", "class_open_service_broker_1_1_completable" ],
      [ "CompletableWithResult", "class_open_service_broker_1_1_completable_with_result.html", "class_open_service_broker_1_1_completable_with_result" ],
      [ "ICompletable", "interface_open_service_broker_1_1_i_completable.html", "interface_open_service_broker_1_1_i_completable" ],
      [ "ICompletableWithResult", "interface_open_service_broker_1_1_i_completable_with_result.html", "interface_open_service_broker_1_1_i_completable_with_result" ],
      [ "IOpenServiceBrokerClient", "interface_open_service_broker_1_1_i_open_service_broker_client.html", "interface_open_service_broker_1_1_i_open_service_broker_client" ],
      [ "IServicePlanReference", "interface_open_service_broker_1_1_i_service_plan_reference.html", null ],
      [ "IUnchangedFlag", "interface_open_service_broker_1_1_i_unchanged_flag.html", "interface_open_service_broker_1_1_i_unchanged_flag" ],
      [ "LastOperationEndpoint", "class_open_service_broker_1_1_last_operation_endpoint.html", "class_open_service_broker_1_1_last_operation_endpoint" ],
      [ "LastOperationResource", "class_open_service_broker_1_1_last_operation_resource.html", "class_open_service_broker_1_1_last_operation_resource" ],
      [ "MaintenanceInfo", "class_open_service_broker_1_1_maintenance_info.html", "class_open_service_broker_1_1_maintenance_info" ],
      [ "MvcBuilderExtensions", "class_open_service_broker_1_1_mvc_builder_extensions.html", "class_open_service_broker_1_1_mvc_builder_extensions" ],
      [ "OpenServiceBrokerClient", "class_open_service_broker_1_1_open_service_broker_client.html", "class_open_service_broker_1_1_open_service_broker_client" ],
      [ "OpenServiceBrokerErrorHandler", "class_open_service_broker_1_1_open_service_broker_error_handler.html", null ],
      [ "OriginatingIdentity", "class_open_service_broker_1_1_originating_identity.html", "class_open_service_broker_1_1_originating_identity" ],
      [ "ServiceBrokerEndpointBase", "class_open_service_broker_1_1_service_broker_endpoint_base.html", "class_open_service_broker_1_1_service_broker_endpoint_base" ]
    ] ]
];